### ISSUE TITLE
cannot run %post script rootless with bootstrap from scratch

### ISSUE THREAD

**Issue by LaHaine** [apptainer/apptainer#809] opened 2022-10-19 14:00 UTC
### Version of Apptainer

What version of Apptainer (or Singularity) are you using? Run

`apptainer --version` (or `singularity --version`).
`apptainer-1.1.2-1.el7.x86_64`

### Expected behavior
It should build the container.

### Actual behavior
It fails with this error:
INFO:    Running post scriptlet
FATAL:   While performing build: while running engine: signal: bad system call

### Steps to reproduce this behavior
It is a bootstrap from scratch definition based on Red Hat Linux 9 (don't ask).
`singularity build RL9.sif RL9.def`
This works as root, but not as user, although the account is in subuid/subgid

### What OS/distro are you running

```sh
$ cat /etc/os-release
NAME="Scientific Linux"
VERSION="7.9 (Nitrogen)"
ID="scientific"
ID_LIKE="rhel centos fedora"
VERSION_ID="7.9"
PRETTY_NAME="Scientific Linux 7.9 (Nitrogen)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:scientificlinux:scientificlinux:7.9:GA"
HOME_URL="http://www.scientificlinux.org//"
BUG_REPORT_URL="mailto:scientific-linux-devel@listserv.fnal.gov"

REDHAT_BUGZILLA_PRODUCT="Scientific Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.9
REDHAT_SUPPORT_PRODUCT="Scientific Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.9"

```

### How did you install Apptainer

Write here how you installed Apptainer (or Singularity). Eg. RPM, source.
EPEL-testing RPM
[packages.txt](https://github.com/apptainer/apptainer/files/9821093/packages.txt)
[RL9.def.txt](https://github.com/apptainer/apptainer/files/9821104/RL9.def.txt)

**Comment by DrDaveD** [comment] 2022-10-20 15:37
Since this is a long-standing problem and will probably need to be fixed by a slightly incompatible change, I am targeting this for 1.2.0.

**Comment by DrDaveD** [comment] 2023-05-30 22:38
Now that 1.2 is getting close I am starting to take a look at this.  I don't have an answer yet, but I found that the bad system call is in the %post step.  This at least makes for faster reproducing of the problem:  if you remove the %post from the original .def file, it successfully builds an image.  Then you can build from with `Boostrap: localimage` and add just the `%post` step and it gets the same failure.

**Comment by DrDaveD** [comment] 2023-05-31 22:08
Another interesting bit of information is that if you run first an apptainer shell using subuid-based fakeroot, then run another apptainer inside of it to do the build adding the %post section, it does not die (for the record: I also set `APPTAINER_BIND= SINGULARITY_BIND=` to prevent it from trying to do nested binds).

That was actually not the behavior I was hoping for because I wanted to use that environment to catch it with strace.  But it could be a workaround for somebody who doesn't have sudo access.

**Comment by DrDaveD** [comment] 2023-05-31 22:32
I got an strace by using apptainer-suid to start the fakeroot and by replacing the starter command (not the starter-suid command) with a wrapper that ran strace, but it wasn't very helpful.  It just ended like this:
```
89    newfstatat(AT_FDCWD, "/.singularity.d/libs/fakeroot",  <unfinished ...>
104   <... epoll_pwait resumed>[], 128, 0, NULL, 1236651) = 0
104   futex(0xc00003e948, FUTEX_WAKE_PRIVATE, 1 <unfinished ...>
105   <... futex resumed>)              = 0
104   <... futex resumed>)              = 1
105   futex(0xc00003e948, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
104   nanosleep({tv_sec=0, tv_nsec=20000}, NULL) = 0
104   futex(0x55882f8afd18, FUTEX_WAIT_PRIVATE, 0, {tv_sec=60, tv_nsec=0} <unfinished ...>
89    <... newfstatat resumed>0xc00040aac8, 0) = -1 ENOENT (No such file or directory)
89    futex(0x55882f8afd18, FUTEX_WAKE_PRIVATE, 1) = 1
104   <... futex resumed>)              = 0
89    execve("/bin/sh", ["/bin/sh", "-ex", "/.post.script"], 0xc000116580 /* 20 vars */ <unfinished ...>
104   getpid()                          = 89
104   tgkill(89, 89, SIGURG)            = 0
```

**Closed** 2023-07-04 15:56 UTC
