### ISSUE TITLE
Time discrepancy between host and container

### ISSUE THREAD

**Issue by lhcamilo** [apptainer/apptainer#1868] opened 2023-12-18 12:52 UTC
### Version of Apptainer

`apptainer version 1.2.5
`

### Expected behaviour

`$ TZ=UTC date --date "2020-01-01T12:00:00" +%s`
`1577880000`

### Actual behaviour

`Apptainer> TZ=UTC date --date "2020-01-01T12:00:00" +%s`
`1577876400`

What actually happened? Why was it incorrect?

It seems the container is running behind by 1 hour. This makes some tests fail. 

### Steps to reproduce this behaviour

1. Build an ubuntu 20.04 with a docker image
2. update in %post
3. run in the shell: 
`TZ=UTC date --date "2020-01-01T12:00:00" +%s`

### What OS/distro are you running

ubuntu 20.04 and rocky linux 8

### How did you install Apptainer

Compiled from source

**Comment by GodloveD** [comment] 2023-12-18 15:49
Since you are giving the date command the timezone and the date that you want to calculate since epoch, I'd say that it is epoch that is incorrect and not the date saved in the container.  I tried to replicate with the same container but I don't see the error.  I wonder if there is a specific setting on your host that is causing this behavior?  Could it have something to do with `/etc/localtime` on your system?

**Comment by DrDaveD** [comment] 2023-12-18 23:18
I see the same behavior with a centos7 host and a container built from docker://centos:7:
```
Apptainer> ls -l /etc/localtime
lrwxrwxrwx 1 dwd fnalgrid 25 Nov 12  2020 /etc/localtime -> ../usr/share/zoneinfo/UTC
Apptainer> date
Mon Dec 18 17:11:51 CST 2023
Apptainer> TZ=UTC date --date "2020-01-01T12:00:00" +%s
1577901600
Apptainer> exit
$ TZ=UTC date --date "2020-01-01T12:00:00" +%s
1577880000
```
So the issue is that apptainer is actually overwriting the UTC time file with my local timezone info, so when you change the timezone to UTC that's what it sees.  You can also see this with
```
Apptainer> date
Mon Dec 18 17:17:22 CST 2023
Apptainer> TZ=UTC date
Mon Dec 18 17:17:27 CST 2023
```
I checked a far back as singularity 3.8 and the behavior is the same.

**Comment by DrDaveD** [comment] 2023-12-19 16:45
We should be able to fix that by checking if /etc/timezone is a symlink in the container, and if the host's is also a symlink and the corresponding path exists in the container, then set the symlink in the container instead of bind-mounting over /etc/timezone.

**Comment by afbjorklund** [comment] 2024-01-03 08:16
There was a related issue, when the `/etc/localtime` symlink was missing from the system altogether:

* #735

**Comment by JasonYangShadow** [comment] 2024-01-05 02:56
I can also confirm the issue when the host's tz is different from container's tz
```
[vagrant@localhost test]$ ls -al /etc/localtime
lrwxrwxrwx. 1 root root 32 Jan  5 11:46 /etc/localtime -> ../usr/share/zoneinfo/Asia/Tokyo
[vagrant@localhost test]$ cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

[vagrant@localhost test]$ apptainer shell centos_7.sif 
INFO:    gocryptfs not found, will not be able to use gocryptfs
Apptainer> ls -al /etc/localtime
lrwxrwxrwx. 1 root root 25 Nov 13  2020 /etc/localtime -> ../usr/share/zoneinfo/UTC
Apptainer> cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

Apptainer> TZ=UTC date --date "2020-01-01T12:00:00" +%s
1577847600
Apptainer> exit
exit
[vagrant@localhost test]$ TZ=UTC date --date "2020-01-01T12:00:00" +%s
1577880000
[vagrant@localhost test]$ apptainer shell centos_7.sif 
INFO:    gocryptfs not found, will not be able to use gocryptfs
Apptainer> date
Fri Jan  5 11:54:05 JST 2024
Apptainer> TZ=UTC date
Fri Jan  5 11:54:13 JST 2024
```

**Comment by akesandgren** [comment] 2024-01-15 08:25
Another way to check this is this little piece of code which is used in R's configure causing builds of R 4.3.2 (at least) to fail when run in a container.
```
#include <stdlib.h>
#include <time.h>
#include <stdio.h>

int main(void) {
    struct tm tm, *stm;
    time_t res;
    putenv("TZ=UTC");
    tm.tm_sec = tm.tm_min = 0; tm.tm_hour = 12;
    tm.tm_mday = 1; tm.tm_mon = 0; tm.tm_year = 120; tm.tm_isdst = 0;
    // test 2020-01-01
    res = mktime(&tm);
    printf("day %ld\n", res);
    printf("isdst = %d\n", tm.tm_isdst);
    printf("tzname[0] = %s, tzname[1] = %s\n", tzname[0], tzname[1]);
    if(res != 1577880000L) {
        printf("ERROR: should be 1577880000L\n");
    }
    exit(0);
}
```

**Comment by DrDaveD** [comment] 2024-03-05 16:38
Probably the easiest fix for this is to create an empty file in the overlay and let it bind onto that instead of trying to remove the symlink.  You may need to remove the symlink in the overlay first.

**Closed** 2024-03-27 17:56 UTC
