### ISSUE TITLE
CentOS/Rocky 8 apptainer/singularity container does not run on CentOS 7

### ISSUE THREAD

**Issue by gregcouch** [apptainer/apptainer#369] opened 2022-04-01 01:08 UTC
### Version of Apptainer:

What version of Apptainer are you using?
```
apptainer version 1.0.1-1
singularity 3.8.7
```

### Expected behavior
I was expecting that a Qt-based application in a CentOS/Rocky 8 container would run on CentOS 7.  It is unclear to me if this is an inherent limitation of apptainer or a bug.  If it is a limitation, it would be helpful if the limitations were prominently documented in the main user documentation.  I've created a test case.  Here is the test.def file:
```
Bootstrap: docker
From: rockylinux:8

%help
Runtime loader bug when executing on CentOS 7 host

%post 
    dnf -y install python3
    python3 -m pip install --upgrade pip
    python3 -m pip install PyQt6

%runscript
    objdump -p /usr/local/lib64/python3.6/site-packages/PyQt6/QtCore.abi3.so 
    objdump -p /usr/local/lib64/python3.6/site-packages/PyQt6/Qt6/lib/libQt6Core.so.6 
    ldd /usr/local/lib64/python3.6/site-packages/PyQt6/QtCore.abi3.so 
    python3 -c "from PyQt6 import QtCore; print('SUCCESS!')"

%environment
    export PATH=/usr/bin:/usr/sbin:/bin:/sbin
    export SHELL=/bin/bash
    export LANG=en_US.UTF-8
```

### Actual behavior

When you ```singularity run test.sil``` on CentOS 7, the last line shows the issue:
```
ImportError: libQt6Core.so.6: cannot open shared object file: No such file or directory
```
That behavior matches the ```libQt6Core.so.6 => not found``` output from ldd, just above.
But if you run it on a CentOS/Rocky 8 host, the last line of output is:
```
SUCCESS!
```

### Steps to reproduce this behavior

Build the container with the above .def file.  Then run it.  It didn't matter if I built the container on CentOS 7 or 8.

### What OS/distro are you running
```
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```

### How did you install Apptainer

I installed apptainer using the rpm after testing with singularity from the epel repo.

**Comment by LaHaine** [comment] 2022-04-01 12:45
This is a problem I have stumbled upon as well. That's caused by Qt5 as built for EL8 has a kernel dependency on the system call renameat2() that is not yet in the EL7 kernel. There's nothing singularity can do about this. Your container will run fine on a system with a newer kernel.

**Comment by gregcouch** [comment] 2022-04-01 22:25
Thank you.  So I guess this is a runtime loader feature.   If you run strace on ldd, you will see that it finds the correct libQt6Core.so.6, and reads the first 832 bytes.  Then it keeps looking in other places.  So it was found, but rejected for some reason.  There's no report of why, even in verbose mode.

**Comment by DrDaveD** [comment] 2022-04-06 21:37
This was also discussed in the [apptainer discuss mailing list](https://groups.google.com/a/apptainer.org/g/discuss/c/qhP4eJrtelk/m/7pGjIDTmAgAJ).  Closing since there's nothing apptainer can do about it.

**Closed by DrDaveD** 2022-04-06 21:37 UTC
