### ISSUE TITLE
Apptainer tries to use overlayfs on a GPFS sandbox (kernel panic)

### ISSUE THREAD

**Issue by sebth** [apptainer/apptainer#2657] opened 2024-11-27 15:59 UTC
### Version of Apptainer

`apptainer version 1.3.5-1.el9`

### Expected behavior

I expect Apptainer to not try to use overlayfs on a sandbox that resides on a GPFS filesystem.

### Actual behavior

When `enable overlay = try`, Apptainer will try overlayfs for sandboxes, even if they reside on a GPFS filesystem:

```
apptainer exec /some/gpfs/filesystem/sandbox echo hello
source: read /.singularity.d/env/01-base.sh: stale NFS file handle
source: read /.singularity.d/env/10-docker2singularity.sh: stale NFS file handle
source: read /.singularity.d/env/90-environment.sh: stale NFS file handle
source: read /.singularity.d/env/94-appsbase.sh: stale NFS file handle
source: read /.singularity.d/env/95-apps.sh: stale NFS file handle
source: read /.singularity.d/env/99-base.sh: stale NFS file handle
FATAL:   failed to open /bin/sh for inspection: failed to open elf binary /bin/sh: read /bin/sh: stale NFS file handle
```

For some sandboxes, GPFS will panic the kernel immediately instead:

```
apptainer exec /some/gpfs/filesystem/sandbox echo hello
[no output -- the kernel has paniced]
```

When `enable overlay = no`, sandboxes on GPFS work:

```
apptainer exec /some/gpfs/filesystem/sandbox echo hello
hello
```

Is this the intended behaviour? I thought the purpose of https://github.com/apptainer/singularity/pull/5279 was to make Apptainer not to try overlayfs on GPFS.

The kernel panic is clearly a bug in GPFS and not Apptainer's fault. We have submitted a bug report to IBM for that.

### What OS/distro are you running

```
NAME="Rocky Linux"
VERSION="9.5 (Blue Onyx)"
ID="rocky"
ID_LIKE="rhel centos fedora"
VERSION_ID="9.5"
PLATFORM_ID="platform:el9"
PRETTY_NAME="Rocky Linux 9.5 (Blue Onyx)"
ANSI_COLOR="0;32"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:rocky:rocky:9::baseos"
HOME_URL="https://rockylinux.org/"
VENDOR_NAME="RESF"
VENDOR_URL="https://resf.org/"
BUG_REPORT_URL="https://bugs.rockylinux.org/"
SUPPORT_END="2032-05-31"
ROCKY_SUPPORT_PRODUCT="Rocky-Linux-9"
ROCKY_SUPPORT_PRODUCT_VERSION="9.5"
REDHAT_SUPPORT_PRODUCT="Rocky Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="9.5"
```

### How did you install Apptainer

From EPEL.

**Comment by DrDaveD** [comment] 2024-11-27 19:12
Thank you for the bug report.  It's not the intended behavior, and I can reproduce it.  It's a regression introduced in 1.3.0; it works as expected in 1.2.5, at least it does for me on the HPC with gpfs I have access to, which is a SUSE SLES 15.4 system.  There in 1.2.5 it doesn't try kernel overlayfs because the `overlay.CheckRootless()` function failed.  That function was removed in 1.3.0 as part of #1937.

A fix is in #2659.  It would be great if you could compile from source with that patch and verify that it works for you.

**Comment by DrDaveD** [comment] 2024-11-27 19:32
Interestingly, I found on the same HPC that attempting to use a sandbox on lustre that the kernel overlayfs gives an `invalid argument` error so apptainer proceeds to use fuse-overlayfs which works.  So this is a GPFS-only problem.

**Comment by sebth** [comment] 2024-11-28 11:00
Patch tested on our HPC: It worked. Thank you!

**Closed** 2024-11-30 13:05 UTC
