### ISSUE TITLE
[Error] cannot install openssh-client correctly

### ISSUE THREAD

**Issue by yingfhu** [apptainer/apptainer#1822] opened 2023-11-23 08:07 UTC
### Version of Apptainer

apptainer version 1.1.0~rc.2-1

### Expected behavior

apt-get update && apt-get install openssh-client

### Actual behavior

Setting up openssh-client (1:7.6p1-4ubuntu0.7) ...                                                                                                                                                                                     
groupadd: failure while writing changes to /etc/group                                                                                                                                                                                  
addgroup: `/usr/sbin/groupadd -g 101 ssh' returned error code 10. Exiting.                                                                                                                                                             
dpkg: error processing package openssh-client (--configure):                                                                                                                                                                           
 installed openssh-client package post-installation script subprocess returned error exit status 1 

### Steps to reproduce this behavior

How can others reproduce this issue/problem?

### What OS/distro are you running

CentOS 7

### How did you install Apptainer

Write here how you installed Apptainer (or Singularity). Eg. RPM, source.

Does it relates to https://github.com/sylabs/singularity/issues/1812

**Comment by yingfhu** [comment] 2023-11-23 08:08
Does it relates to https://github.com/sylabs/singularity/issues/1812

**Comment by willfurnass** [comment] 2024-03-20 12:44
A possible workaround is to disable the post-install script for the `openssh-client` Ubuntu .deb package e.g.
```bash
  export DEBIAN_FRONTEND=noninteractive
  apt-get update
  apt-get install -y `apt-cache depends openssh-client | awk '/Depends:/{print$2}'`
  apt-get download openssh-client
  dpkg --unpack openssh-client*.deb
  rm /var/lib/dpkg/info/openssh-client.postinst -f
  dpkg --configure openssh-client
  ...
  ```

**Comment by willfurnass** [comment] 2024-03-20 12:46
Also, I can confirm that the error msg shown in the original post can be seen/reproduced if one is trying to build an image using just `fakeroot` on CentOS 7 and the following image recipe:
```
Bootstrap: docker
From: ubuntu:22.04
%post
  export DEBIAN_FRONTEND=noninteractive
  apt-get update && apt-get install -y openssh-client
  ```

**Comment by DrDaveD** [comment] 2024-03-21 15:44
Closing since the submitter stopped responding

**Closed by DrDaveD** 2024-03-21 15:44 UTC

**Comment by kkaulen** [comment] 2024-04-12 11:29
Can reproduce on our compute cluster running Apptainer 1.3.0-1.el8. On my local machine running 1.2.5-1.el7 everything works as expected.
If your goal is to install a package depending on the ssh-client but not really needing it (e.g. just needing git over HTTPS) or not requiring the most recent version, I suggest the following workaround:

```
Bootstrap: docker
From: nvidia/cuda:12.4.1-devel-ubuntu20.04

%post
    apt-get update && \
    apt-mark hold openssh-client && \           # this prevents apt from updating the ssh client
    apt-get -y install git

```

**Comment by DrDaveD** [comment] 2024-04-15 19:26
@kkaulen Thanks for the workaround, but please also submit a new issue with complete info about your environment and steps to reproduce.
