### ISSUE TITLE
add ability to checkpoint container to storage device as first class option

### ISSUE THREAD

**Issue by PaulCharlton** [apptainer/apptainer#37] opened 2021-12-05 05:54 UTC
add ability to checkpoint container to storage device as first class option.

At the moment, checkpoint capability is available via the plugin module from lancium
at [checkpoint plugin](https://github.com/lancium/dmtcp-singularity-plugin)

**Comment by DrDaveD** [comment] 2021-12-06 16:34
Duplicate of #16

**Closed by DrDaveD** 2021-12-06 16:34 UTC
