### ISSUE TITLE
Segmentation fault with docker image with apptainer (on an image that did not segfault with singularity)

### ISSUE THREAD

**Issue by khurtado** [apptainer/apptainer#534] opened 2022-07-06 10:51 UTC
### Version of Apptainer

```
$ singularity --version
apptainer version 1.0.2-1.el8
```
I'm trying this command with the following image in docker hub, getting a Segmentation fault.
```
$ SINGULARITY_CACHEDIR=/tmp APPTAINER_CACHEDIR=/tmp singularity exec docker://madminertool/madminer-workflow-ph:0.5.3beta16 echo hello
<snip>
INFO:    Using cached SIF image
Segmentation fault
```

### Expected behavior
The container should run and I display "hello"

### Actual behavior

I get a Segmentation fault instead. 
Singularity 3.8.7 works though

```
$ SINGULARITY_CACHEDIR=/tmp singularity exec docker://madminertool/madminer-workflow-ph:0.5.3beta16 echo hello
INFO:    Creating SIF file...
hello
$ singularity --version
singularity version 3.8.7-1.el7
```

### Steps to reproduce this behavior

You can try the following command:
```
$ SINGULARITY_CACHEDIR=/tmp APPTAINER_CACHEDIR=/tmp singularity exec docker://madminertool/madminer-workflow-ph:0.5.3beta16 echo hello
```

### What OS/distro are you running

Red Hat Enterprise Linux release 8.6 (Ootpa)

### How did you install Apptainer

RPM source
```
Name         : apptainer
Version      : 1.0.2
Release      : 1.el8
Architecture : x86_64
Size         : 128 M
Source       : apptainer-1.0.2-1.el8.src.rpm
Repository   : @System
From repo    : @commandline
Summary      : Application and environment virtualization
URL          : https://apptainer.org
License      : BSD and LBNL BSD and ASL 2.0
Description  : Apptainer provides functionality to make portable
             : containers that can be used across host environments.
```

**Comment by DrDaveD** [comment] 2022-07-06 19:44
The command succeeded for me on my centos7 VM.  I have not been able to yet build the SIF image on my rocky8 VM because it doesn't have enough disk space, despite freeing up over 8G and removing the ~2G of docker cache during the build phase.  I made a .sif file out of the docker source on centos7, copied the file to rocky8, and that did not reproduce the problem either, it did not crash.

For the next step run it with '-d' to at least show whether the segfault is happening inside the container itself or somewhere earlier in apptainer.

**Comment by khurtado** [comment] 2022-07-06 20:27
It seems this might be due to AFS or something in my HOME area. If I execute singularity from my home area, it seg faults.
But if I switch to `/tmp` before doing so, then it works. What could be causing this behavior?

```
[khurtado@bastion ~]$ SINGULARITY_CACHEDIR=/tmp APPTAINER_CACHEDIR=/tmp singularity exec docker://madminertool/madminer-workflow-ph:0.5.3beta16 echo hello
INFO:    Using cached SIF image
Segmentation fault
[khurtado@bastion ~]$ cd /tmp
[khurtado@bastion /tmp]$ SINGULARITY_CACHEDIR=/tmp APPTAINER_CACHEDIR=/tmp singularity exec docker://madminertool/madminer-workflow-ph:0.5.3beta16 echo hello
INFO:    Using cached SIF image
hello
```

**Comment by DrDaveD** [comment] 2022-07-06 20:37
I have no idea since it could be happening in many different places.  The -d option and/or strace could narrow it down.

**Comment by khurtado** [comment] 2022-07-06 20:44
@DrDaveD 

I did paste the command output with the `-d` when it seg faults.

https://gist.githubusercontent.com/khurtado/f3a806d660c0ee5887b53372d19e2305/raw/b70faa5990de6040801b3dce4660175dd1a480d2/Apptainer_debug.log

Here is the one from strace:

https://gist.github.com/khurtado/d42f940d9f20e7ca124be8c62c044ec6

**Comment by DrDaveD** [comment] 2022-07-06 21:04
No, the -d shows that it is dying inside the container, after apptainer has done all its work:
```
DEBUG   [U=211834,P=3668766]sylogBuiltin()                Sourcing /.singularity.d/env/01-base.sh
DEBUG   [U=211834,P=3668766]sylogBuiltin()                Sourcing /.singularity.d/env/10-docker2singularity.sh
DEBUG   [U=211834,P=3668766]sylogBuiltin()                Sourcing /.singularity.d/env/90-environment.sh
DEBUG   [U=211834,P=3668766]sylogBuiltin()                Sourcing /.singularity.d/env/94-appsbase.sh
DEBUG   [U=211834,P=3668766]sylogBuiltin()                Sourcing /.singularity.d/env/95-apps.sh
DEBUG   [U=211834,P=3668766]sylogBuiltin()                Sourcing /.singularity.d/env/99-base.sh
DEBUG   [U=211834,P=3668766]sylogBuiltin()                Sourcing /.singularity.d/env/99-runtimevars.sh
DEBUG   [U=211834,P=3668766]sylogBuiltin()                Running action command exec
DEBUG   [U=211834,P=3654517]PostStartProcess()            Post start process
DEBUG   [U=211834,P=3654517]Master()                      Child exited due to signal 11
Segmentation fault
```

You would need to add '-f' to the strace command line in order for it to be helpful.  The output will get a lot longer.

**Comment by khurtado** [comment] 2022-07-06 21:40
@DrDaveD I asked our system admin to run it, as I didn't let me run as a user 

Here is the output:

https://gist.github.com/khurtado/3124129e7c6b493aed2361bd223bfebe

**Comment by DrDaveD** [comment] 2022-07-06 21:45
Unfortunately that also stops too soon, as it execs the setuid portion.  I forgot about that.  Do you have unprivileged user namespaces available, such that you can use the `exec -u` option?  It is by default enabled on el8 hosts.  If that still seg faults, you should be able to get a complete `strace -f`.

**Comment by khurtado** [comment] 2022-07-07 21:24
If I try `-u`, it works with other images like alpine, but I get a setuid error with this one in particular

```
$ strace -o /tmp/singu_u.log -f env -i SINGULARITY_CACHEDIR=/tmp/sin APPTAINER_CACHEDIR=/tmp/sin singularity exec -u docker://madminertool/madminer-workflow-ph:0.5.3beta16 echo hello
INFO:    Using cached SIF image
INFO:    Converting SIF file to temporary sandbox...
FATAL:   while extracting /tmp/sin/cache/oci-tmp/db280a142509e34dddcfc847f9d97d3a934af9cd870a777a30fd6ac662119082: root filesystem extraction failed: extract command failed: ERROR  : Failed to set effective UID to 0
: exit status 1
```
Here is the strace output anyway:
https://gist.githubusercontent.com/khurtado/b995d5bbf0e0e4409644f3b1fa62b46d/raw/a9d36220f3c3dc6e654c539399b2c26a5150c0f1/singu_u.log

**Comment by DrDaveD** [comment] 2022-07-07 22:20
Darn, I forgot about the need for converting to sandbox when running with -u on the released apptainer.  The current main branch doesn't require that because it will mount with squashfuse, but besides requiring you to compile from source that might also change the behavior.

I'm afraid that you might not get the segfault with a sandbox either, but please try
```
SINGULARITY_CACHEDIR=/tmp/sin APPTAINER_CACHEDIR=/tmp/sin singularity build --sandbox madminer-sandbox docker://madminertool/madminer-workflow-ph:0.5.3beta16
singularity exec -u madminer-sandbox echo hello
```
If that does give the segfault, great, then run strace -f on the exec command only.

**Comment by khurtado** [comment] 2022-07-08 15:47
The first command gave me a "permission denied" error whne done from my AFS home area. I do have my token alive and am able to write as a user.

```
(base) [khurtado@bastion ~]$ SINGULARITY_CACHEDIR=/tmp/sin APPTAINER_CACHEDIR=/tmp/sin singularity build --sandbox madminer-sandbox docker://madminertool/madminer-workflow-ph:0.5.3beta16
INFO:    Starting build...
Getting image source signatures
Copying blob 345e3491a907 [--------------------------------------] 0.0b / 27.2MiB
Copying blob 57671312ef6f [--------------------------------------] 0.0b / 851.0b
Copying blob 5e9250ddb7d0 [--------------------------------------] 0.0b / 187.0b
Copying blob 6728aa448e29 [--------------------------------------] 0.0b / 375.0b
Copying blob 7d5533619f4b [--------------------------------------] 0.0b / 500.6MiB
Copying blob f454a1c8a167 [--------------------------------------] 0.0b / 79.5MiB
Copying blob efcf39ea924f [--------------------------------------] 0.0b / 16.7KiB
Copying blob c7c8529f6ab9 [--------------------------------------] 0.0b / 1.9KiB
Copying blob e1b70d94d5fa [--------------------------------------] 0.0b / 246.0b
Copying blob b2299e796965 [--------------------------------------] 0.0b / 941.8MiB
Copying blob d0fbcafea22f [--------------------------------------] 0.0b / 32.2MiB
Copying blob 6f2288ee2778 [--------------------------------------] 0.0b / 2.3MiB
Copying blob 63782ff40362 [--------------------------------------] 0.0b / 96.3MiB
Copying blob 858d0297e36c [--------------------------------------] 0.0b / 37.2MiB
Copying blob 6d67e3e94e34 [--------------------------------------] 0.0b / 5.5KiB
Copying blob 994936c18d6c [--------------------------------------] 0.0b / 89.7KiB
Copying config 4bdfbe7de8 done
Writing manifest to image destination
Storing signatures
2022/07/08 11:45:29  info unpack layer: sha256:345e3491a907bb7c6f1bdddcf4a94284b8b6ddd77eb7d93f09432b17b20f2bbe
2022/07/08 11:45:29  warn xattr{etc/gshadow} ignoring ENOTSUP on setxattr "user.rootlesscontainers"
2022/07/08 11:45:29  warn xattr{/afs/crc.nd.edu/user/k/khurtado/build-temp-1407658807/rootfs/etc/gshadow} destination filesystem does not support xattrs, further warnings will be suppressed
FATAL:   While performing build: packer failed to pack: while unpacking tmpfs: error unpacking rootfs: unpack layer: unpack entry: var/local: apply hdr metadata: restore chmod metadata: /afs/crc.nd.edu/user/k/khurtado/build-temp-1407658807/rootfs/var/local: unpriv.chmod: chmod /afs/crc.nd.edu/user/k/khurtado/build-temp-1407658807/rootfs/var/local: permission denied
```

**Comment by DrDaveD** [comment] 2022-07-08 17:03
That's weird.  Anyway that step is TMPDIR, so try setting APPTAINER_TMPDIR to the same value as APPTAINER_CACHEDIR.  You may still get an error in the final step where it creates the sandbox itself.

**Comment by khurtado** [comment] 2022-07-08 18:10
I didn't notice any change after setting that variable:

```
(base) [khurtado@bastion ~]$ SINGULARITY_TMPDIR=/tmp/sin APPTAINER_TMPDIR=/tmp/sin SINGULARITY_CACHEDIR=/tmp/sin APPTAINER_CACHEDIR=/tmp/sin singularity build --sandbox madminer-sandbox docker://madminertool/madminer-workflow-ph:0.5.3beta16
INFO:    Starting build...
Getting image source signatures
Copying blob 345e3491a907 [--------------------------------------] 0.0b / 27.2MiB
Copying blob 57671312ef6f [--------------------------------------] 0.0b / 851.0b
Copying blob 5e9250ddb7d0 [--------------------------------------] 0.0b / 187.0b
Copying blob 6728aa448e29 [--------------------------------------] 0.0b / 375.0b
Copying blob 7d5533619f4b [--------------------------------------] 0.0b / 500.6MiB
Copying blob f454a1c8a167 [--------------------------------------] 0.0b / 79.5MiB
Copying blob efcf39ea924f [--------------------------------------] 0.0b / 16.7KiB
Copying blob c7c8529f6ab9 [--------------------------------------] 0.0b / 1.9KiB
Copying blob e1b70d94d5fa [--------------------------------------] 0.0b / 246.0b
Copying blob b2299e796965 [--------------------------------------] 0.0b / 941.8MiB
Copying blob d0fbcafea22f [--------------------------------------] 0.0b / 32.2MiB
Copying blob 6f2288ee2778 [--------------------------------------] 0.0b / 2.3MiB
Copying blob 63782ff40362 [--------------------------------------] 0.0b / 96.3MiB
Copying blob 858d0297e36c [--------------------------------------] 0.0b / 37.2MiB
Copying blob 6d67e3e94e34 [--------------------------------------] 0.0b / 5.5KiB
Copying blob 994936c18d6c [--------------------------------------] 0.0b / 89.7KiB
Copying config 4bdfbe7de8 done
Writing manifest to image destination
Storing signatures
2022/07/08 14:08:26  info unpack layer: sha256:345e3491a907bb7c6f1bdddcf4a94284b8b6ddd77eb7d93f09432b17b20f2bbe
2022/07/08 14:08:26  warn xattr{etc/gshadow} ignoring ENOTSUP on setxattr "user.rootlesscontainers"
2022/07/08 14:08:26  warn xattr{/afs/crc.nd.edu/user/k/khurtado/build-temp-888571015/rootfs/etc/gshadow} destination filesystem does not support xattrs, further warnings will be suppressed
FATAL:   While performing build: packer failed to pack: while unpacking tmpfs: error unpacking rootfs: unpack layer: unpack entry: var/local: apply hdr metadata: restore chmod metadata: /afs/crc.nd.edu/user/k/khurtado/build-temp-888571015/rootfs/var/local: unpriv.chmod: chmod /afs/crc.nd.edu/user/k/khurtado/build-temp-888571015/rootfs/var/local: permission denied
```

**Comment by DrDaveD** [comment] 2022-07-08 19:12
You're right.  I can reproduce it, and I see in the code that it is deliberately putting that temporary directory in the same directory as the sandbox destination.  It must intend to just rename it when finished.  (I did see that an earlier step, the "bundle-temp", did get put into the APPTAINER_TMPDIR).

Ok, so my next theory is that it has to do with AFS weird interpretation of directory permissions.  Try using the --fix-perms option.  

I hit a different problem on my NFSv4 home directory.  It got this error right after "Storing Signatures" (even with --fix-perms):
```
FATAL:   While performing build: packer failed to pack: while unpacking tmpfs: error unpacking rootfs: chown rootfs: lchown /nashome/d/dwd/work/apptainer/internal/build-temp-3838764288/rootfs: operation not permitted
```
I was able to build it on local disk even without `--fix-perms` and then mv the whole sandbox over to NFS.  Maybe that could be the fallback for you if building on AFS directly with `--fix-perms` doesn't work at all.

**Comment by DrDaveD** [comment] 2022-07-22 02:28
Well, that helps narrow it down some but it's still really hard to tell a root cause.

The first "SIGSEGV" is
```
10617  2990451 --- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0x18} ---
```
and the process 2990451 is /usr/bin/echo inside the container, not apptainer itself.  All the lines relevant to that process are:
```
2990451 execve("/usr/bin/echo", ["/usr/bin/echo", "hello"], 0xc0002ba600 /* 91 vars */ <unfinished ...>
2990451 <... execve resumed>)           = 0
2990451 brk(NULL <unfinished ...>
2990451 <... brk resumed>)              = 0x55c642984000
2990451 arch_prctl(0x3001 /* ARCH_??? */, 0x7ffc227c5830 <unfinished ...>
2990451 <... arch_prctl resumed>)       = -1 EINVAL (Invalid argument)
2990451 access("/etc/ld.so.preload", R_OK <unfinished ...>
2990451 <... access resumed>)           = -1 ENOENT (No such file or directory)
2990451 openat(AT_FDCWD, "tls/x86_64/x86_64/libc.so.6", O_RDONLY|O_CLOEXEC <unfinished ...>
2990451 <... openat resumed>)           = -1 ENOENT (No such file or directory)
2990451 openat(AT_FDCWD, "tls/x86_64/libc.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
2990451 openat(AT_FDCWD, "tls/x86_64/libc.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
2990451 openat(AT_FDCWD, "tls/libc.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
2990451 openat(AT_FDCWD, "x86_64/x86_64/libc.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
2990451 openat(AT_FDCWD, "x86_64/libc.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
2990451 openat(AT_FDCWD, "x86_64/libc.so.6", O_RDONLY|O_CLOEXEC <unfinished ...>
2990451 <... openat resumed>)           = -1 ENOENT (No such file or directory)
2990451 openat(AT_FDCWD, "libc.so.6", O_RDONLY|O_CLOEXEC) = 3
2990451 read(3, "\177ELF\2\1\1\3\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0`&\2\0\0\0\0\0"..., 832) = 832
2990451 fstat(3, {st_mode=S_IFREG|0755, st_size=2156592, ...}) = 0
2990451 mmap(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fa0e9b4a000
2990451 getcwd("/afs/crc.nd.edu/user/k/khurtado", 128) = 32
2990451 mmap(NULL, 3985920, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7fa0e977c000
2990451 mprotect(0x7fa0e9940000, 2093056, PROT_NONE) = 0
2990451 mmap(0x7fa0e9b3f000, 24576, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x1c3000) = 0x7fa0e9b3f000
2990451 mmap(0x7fa0e9b45000, 16896, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7fa0e9b45000
2990451 close(3)                        = 0
2990451 arch_prctl(ARCH_SET_FS, 0x7fa0e9b4b500) = 0
2990451 access("/etc/sysconfig/strcasecmp-nonascii", F_OK) = -1 ENOENT (No such file or directory)
2990451 access("/etc/sysconfig/strcasecmp-nonascii", F_OK) = -1 ENOENT (No such file or directory)
2990451 mprotect(0x7fa0e9b3f000, 16384, PROT_READ) = 0
2990451 mprotect(0x55c64159c000, 4096, PROT_READ) = 0
2990451 mprotect(0x7fa0e9b79000, 4096, PROT_READ) = 0
2990451 --- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0x18} ---
```
I don't understand why echo is doing `getcwd()`.  When I strace echo on my machine I don't see that.  What is the operating system that the container is built on?  Do you see a segfault if you run something else, such as `cat /etc/os-release`?

**Comment by khurtado** [comment] 2022-07-22 20:15
It's Ubuntu 20.04. `cat /etc/-os-release` does produce a segfault from AFS

What worked though, was using `-c`
```
(base) [khurtado@bastion ~]$ singularity exec -u madminer-sandbox cat /etc/os-release
Segmentation fault (core dumped)
(base) [khurtado@bastion ~]$ singularity exec -c -u madminer-sandbox echo hello
hello
```

What worked though

**Comment by DrDaveD** [comment] 2022-07-22 21:08
Well, yes, -c makes an empty home directory so that would be different.

I do not see the same behavior on my Ubuntu 20.04; echo does not read getcwd().

In fact, I do not even see the same behavior on that madminer container.  Where it sees
```
2990451 openat(AT_FDCWD, "libc.so.6", O_RDONLY|O_CLOEXEC) = 3
```
I see
```
18167 openat(AT_FDCWD, "libc.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such fil
e or directory)
```
and it eventually goes to open libc.so.6 at
```
18167 openat(AT_FDCWD, "/lib/x86_64-linux-gnu/libc.so.6", O_RDONLY|O_CLOEXEC) = 3
```

Do you have a libc.so.6 in your home directory?

**Comment by khurtado** [comment] 2022-07-22 21:21
@DrDaveD Yes! I I didn't even notice. if I move libc libraries out of my AFS home directory, it works wth `-u`, but seems to hang without it.

```
(base) [khurtado@bastion ~]$ singularity exec -u madminer-sandbox echo hello
hello
(base) [khurtado@bastion ~]$ SINGULARITY_CACHEDIR=/tmp APPTAINER_CACHEDIR=/tmp singularity exec madminer-sandbox echo hello
source: read /.singularity.d/env/01-base.sh: input/output error
```

**Comment by DrDaveD** [comment] 2022-07-22 21:36
That's a new problem, although you weren't running a sandbox out of AFS before.  I suspect the suid flow is somehow interfering with your AFS authentication.  Try it with a .sif file again or even the docker:// URL which should end up using the .sif from your cache.

I don't think APPTAINER_CACHEDIR gets used when running from a sandbox or sif, although it is used when running from docker.

**Comment by khurtado** [comment] 2022-07-23 01:58
@DrDaveD It works! Sorry about the noise. 
I had no idea having libc files in the home directory could produce such a problem.

```
(base) [khurtado@bastion ~]$ SINGULARITY_CACHEDIR=/tmp APPTAINER_CACHEDIR=/tmp singularity exec docker://madminertool/madminer-workflow-ph:0.5.3beta16 echo hello
INFO:    Using cached SIF image
hello
(base) [khurtado@bastion ~]$ pwd
/afs/crc.nd.edu/user/k/khurtado
(base) [khurtado@bastion ~]$
```

**Comment by DrDaveD** [comment] 2022-07-23 16:04
I think the problem is something peculiar to that image.  I don't think that normally the current directory is searched for libraries.  

Closing, since the problem is solved and not anything apptainer is doing wrong.

**Closed by DrDaveD** 2022-07-23 16:04 UTC
