### ISSUE TITLE
Provide generic files names for releases

### ISSUE THREAD

**Issue by MikeKroell** [apptainer/apptainer#713] opened 2022-09-22 14:25 UTC
Currently, within the AppTainer GitHub file downloads on releases, they include the version number.  This does not make it possible to use the "latest" link to ensure that when pulled, we always get the latest stable release:

https://github.com/apptainer/apptainer/releases/latest/download/

The file must be the same name throughout the release for its functionality to work properly. Something like:

https://github.com/apptainer/apptainer/releases/latest/download/apptainer.x86_64.rpm

**Comment by DrDaveD** [comment] 2022-09-22 22:04
Very cool, I had no idea that "latest" was a thing on github.

However, I hesitate to make remove the version numbers from all of them for this feature.  There are a lot of files there and I'd hate to make an extra duplicate of all of them.

How about using a script based on extracting the latest version number with
```
curl -vs https://github.com/apptainer/apptainer/releases/latest/download 2>&1|sed -n 's,^< Location: .*/v,,p'
```

**Comment by MikeKroell** [comment] 2022-09-22 22:10
So this is a start, but this doesn't appear to be fix because it looks like the files sometimes have an extra number in the file name. Your command gives back 1.0.3, but the file has 1.0.3-1. I'm not an expert, but is there a way to do both? You could also do it moving forward to not break any past releases.

![image](https://user-images.githubusercontent.com/48728771/191860028-d62e96be-0652-42c4-be5f-dd1a5d323efe.png)

**Comment by DrDaveD** [comment] 2022-09-22 22:48
You should be able to safely assume that rpms will always have a `-1`.

**Comment by DrDaveD** [comment] 2022-09-22 22:48
We could do both, but I really don't want to double the list of assets for this.

**Comment by MikeKroell** [comment] 2022-09-23 00:33
Understandable. If you can commit to the file naming, we can work with that. Can you document it for others? Officially supported bash script to always pull latest?

**Comment by DrDaveD** [comment] 2022-09-23 14:01
A bash script in the top level directory sounds like a good idea to me, one that could install either rpm or deb depending on what is in `/etc/os-release`.  Would you be willing to take the first crack at it with a pull request?

**Comment by afbjorklund** [comment] 2022-10-02 07:49
> You should be able to safely assume that rpms will always have a `-1`.

We had the same issue in minikube, because it was impossible to agree on who would host the apt and yum repositories.

We used "0" for the release, to get less hate from distributions that normally start their packaging on "1" or "1.fc38" or so ?

But did not find a good way to fix the original problem, so ended up having to duplicate each package for each architecture:

https://github.com/kubernetes/minikube/releases/latest

**Closed** 2022-12-09 16:59 UTC
