### ISSUE TITLE
Apptainer 1.3.0 uses wrong mediaType in manifest

### ISSUE THREAD

**Issue by anderbubble** [apptainer/apptainer#2178] opened 2024-04-23 20:50 UTC
### Version of Apptainer

1.3.0 (comparing with 1.2.5).

### Expected behavior

When using Apptainer v1.2.5 to push a SIF to an ORAS registry

```
apptainer push container.sif oras://[redacted]/container.sif:apptainer-1.2.5
```

it is recorded with a manifest like this:

```
# ./oras manifest fetch [redacted]/container.sif:apptainer-1.2.5 | jq
{
  "schemaVersion": 2,
  "config": {
    "mediaType": "application/vnd.unknown.config.v1+json",
    "digest": "sha256:44136fa355b3678a1146ad16f7e8649e94fb4fc21fe77e8310c060f61caaff8a",
    "size": 2
  },
  "layers": [
    {
      "mediaType": "application/vnd.sylabs.sif.layer.v1.sif",
      "digest": "sha256:c832a28d73c64917b3d309536bc42a42770465bbafafcd7088034ac65d8206bf",
      "size": 1076219904,
      "annotations": {
        "org.opencontainers.image.title": "container.sif"
      }
    }
  ]
}
```

### Actual behavior

When using Apptainer v1.3.0 to push a SIF to an ORAS registry

```
apptainer push container.sif oras://[redacted]/container.sif:apptainer-1.3.0
```

it is recorded with a manifest like this:

```
# ./oras manifest fetch [redacted]/container.sif:apptainer-1.3.0 | jq
{
  "schemaVersion": 2,
  "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
  "config": {
    "mediaType": "application/vnd.sylabs.sif.config.v1+json",
    "size": 2,
    "digest": "sha256:44136fa355b3678a1146ad16f7e8649e94fb4fc21fe77e8310c060f61caaff8a"
  },
  "layers": [
    {
      "mediaType": "application/vnd.sylabs.sif.layer.v1.sif",
      "size": 1076219904,
      "digest": "sha256:c832a28d73c64917b3d309536bc42a42770465bbafafcd7088034ac65d8206bf",
      "annotations": {
        "org.opencontainers.image.title": "container.sif"
      }
    }
  ]
}
```

The outer `"mediaType": "application/vnd.docker.distribution.manifest.v2+json",` leads to `Content-Type: application/vnd.docker.distribution.manifest.v2+json` which leads peer applications to interpret the artifact as a Docker container rather than a SIF.

I understand that the correct content-type for SIF images should be `Content-Type: application/vnd.oci.image.manifest.v1+json`.

(Apptainer itself doesn't have this issue at pull time because Apptainer assumes the image format from parsing the URL, `docker://` vs `oras://`.)

### Steps to reproduce this behavior

With Apptainer 1.3.0:

```
# apptainer push container.sif oras://registry/container.sif
# ./oras manifest fetch [redacted]/container.sif:apptainer-1.3.0 | jq
```

### What OS/distro are you running

```sh
# cat /etc/os-release 
NAME="Rocky Linux"
VERSION="8.9 (Green Obsidian)"
ID="rocky"
ID_LIKE="rhel centos fedora"
VERSION_ID="8.9"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Rocky Linux 8.9 (Green Obsidian)"
ANSI_COLOR="0;32"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:rocky:rocky:8:GA"
HOME_URL="https://rockylinux.org/"
BUG_REPORT_URL="https://bugs.rockylinux.org/"
SUPPORT_END="2029-05-31"
ROCKY_SUPPORT_PRODUCT="Rocky-Linux-8"
ROCKY_SUPPORT_PRODUCT_VERSION="8.9"
REDHAT_SUPPORT_PRODUCT="Rocky Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.9"

```

### How did you install Apptainer

EPEL RPM for 1.3.0. (GitHub release RPM for 1.2.5 comparison.)

**Comment by DrDaveD** [comment] 2024-04-23 21:29
I don't know much about this.  Hopefully @JasonYangShadow can figure it out.  

We had planned on releasing 1.3.1 today but maybe we can delay it a day if a fix for this could be made right away.

**Comment by anderbubble** [comment] 2024-04-23 21:32
@cclerget might have some insight, too.

**Comment by JasonYangShadow** [comment] 2024-04-24 00:38
@DrDaveD @anderbubble cc @cclerget 
I think it is caused by this code
https://github.com/JasonYangShadow/apptainer/blob/58e8852f63b78e878be36d0e1cec8e0c121309e7/internal/pkg/client/oras/image.go#L150

**Closed** 2024-04-24 12:13 UTC
