### ISSUE TITLE
Fakeroot and GLIBC

### ISSUE THREAD

**Issue by matekelemen** [apptainer/apptainer#1758] opened 2023-10-21 23:32 UTC
## Issue

I'm trying to build an image that uses [`rocm/pytorch:latest`](https://rocm.docs.amd.com/en/latest/how_to/pytorch_install/pytorch_install.html) as its base, but as soon as I hit `%post`:
```
...
INFO:    Running post scriptlet
/.singularity.d/libs/faked: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /.singularity.d/libs/faked)
/.singularity.d/libs/faked: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /.singularity.d/libs/faked)
fakeroot: error while starting the `faked' daemon.
/.singularity.d/libs/fakeroot: 1: kill: Usage: kill [-s sigspec | -signum | -sigspec] [pid | job]... or
kill -l [exitstatus]
FATAL:   While performing build: while running engine: exit status 1
```

My definition file:
```
Bootstrap: docker
From: rocm/pytorch:latest

%post
    apt-get upate
```

Unsurprisingly, if I delete the `%post` section, the image is built just fine.

## Details

This issue is actually [mentioned](https://apptainer.org/docs/user/main/fakeroot.html#overview) in the docs, but I'm confused by the proposed solution. Here's what I understand:
- my GLIBC (version 2.38) is several versions ahead of what fakeroot inside the image expects (version 2.31, why is this a problem though?! I'm under the impression that GLIBC is backward compatible)
- the [proposed solution](https://apptainer.org/docs/admin/main/installation.html#install-unprivileged-from-pre-built-binaries) is to locally install a version of `apptainer` that was built using an older toolchain.
- however, this [script](https://github.com/apptainer/apptainer/blob/73e06fc047c89bfba1b3c51a3dac75136a1f2d4e/tools/install-unprivileged.sh) seems to rely on being executed on extremely conservative distros, which completely ignores the cause of the issue (the host system is too recent compared to the base image). I ran into the following problems while trying to execute it:
   - `arch` is not a command I've ever heard before. That's an easy fix with `uname -m` though
   - being an Arch-based distro, Manjaro doesn't have `rpm2cpio` or `cpio`. They can be installed from [rpmextract](https://archlinux.org/packages/extra/any/rpmextract/) and [cpio](https://archlinux.org/packages/extra/x86_64/cpio/) respectively, but I doubt they are the required versions, because of follow-up issues:
   - the script seems to rely on `rpm2cpio` being able to handle input from the pipe, but that's not the case on my system because `rpm2cpio` is just the following script:

```
#!/bin/sh

pkg=$1
if [ "$pkg" = "" -o ! -e "$pkg" ]; then
    echo "no package supplied" 1>&2
   exit 1
fi

leadsize=96
o=`expr $leadsize + 8`
set `od -j $o -N 8 -t u1 $pkg`
il=`expr 256 \* \( 256 \* \( 256 \* $2 + $3 \) + $4 \) + $5`
dl=`expr 256 \* \( 256 \* \( 256 \* $6 + $7 \) + $8 \) + $9`

sigsize=`expr 8 + 16 \* $il + $dl`
o=`expr $o + $sigsize + \( 8 - \( $sigsize \% 8 \) \) \% 8 + 8`
set `od -j $o -N 8 -t u1 $pkg`
il=`expr 256 \* \( 256 \* \( 256 \* $2 + $3 \) + $4 \) + $5`
dl=`expr 256 \* \( 256 \* \( 256 \* $6 + $7 \) + $8 \) + $9`

hdrsize=`expr 8 + 16 \* $il + $dl`
o=`expr $o + $hdrsize`

dd if=$pkg ibs=$o skip=1 2>/dev/null | gunzip
```
   - that's still solvable: I changed to script to save the downloaded `rpm` packages and then pass them to `rpm2cpio` instead of directly piping it.
   - however, the output from `rpm2cpio` is not digestible by `cpio` because:
```
cpio: Malformed number �
cpio: Malformed number �����@��
cpio: Malformed number ����@��.
cpio: Malformed number ���@��.�
cpio: Malformed number ��@��.��
cpio: Malformed number �@��.���
cpio: Malformed number @��.����
cpio: Malformed number ��.����c
cpio: Malformed number �.����c�
cpio: Malformed number .����c�k
cpio: Malformed number ����c�k�
cpio: Malformed number ���c�k�m
cpio: warning: skipped 3722 bytes of junk
cpio: malformed header: file name is not nul-terminated
cpio: premature end of file
Error extracting /home/whatever/tmp/apptainer-1.2.4-1.el7.x86_64.rpm
```
   - I found a [hint](https://stackoverflow.com/questions/18787375/how-do-i-extract-the-contents-of-an-rpm) on stackoverflow about the package possibly being packed, so I fed the output through `xz` before piping it into `cpio` (`rpm2cpio <file>.rpm | xz -d | cpio -idum`)
   - a few packages could be extracted like that, but then:

```
Extracting https://linux-mirrors.fnal.gov/linux/centos/7/os/x86_64/Packages/lzo-2.06-8.el7.x86_64.rpm
od: cannot skip past end of combined input
xz: (stdin): File format not recognized
cpio: premature end of archive
failure extracting https://linux-mirrors.fnal.gov/linux/centos/7/os/x86_64/Packages/lzo-2.06-8.el7.x86_64.rpm
```

... and now I'm out of my depth. Am I even supposed to use this script, or is it meant for specific distros? My main goal is to build on top of the `rocm/pytorch:latest` docker image.

## Host Environment

```
apptainer --version
apptainer version 1.2.2
```

```sh
cat /etc/os-release
NAME="Manjaro Linux"
PRETTY_NAME="Manjaro Linux"
ID=manjaro
ID_LIKE=arch
BUILD_ID=rolling
ANSI_COLOR="32;1;24;144;200"
HOME_URL="https://manjaro.org/"
DOCUMENTATION_URL="https://wiki.manjaro.org/"
SUPPORT_URL="https://forum.manjaro.org/"
BUG_REPORT_URL="https://docs.manjaro.org/reporting-bugs/"
PRIVACY_POLICY_URL="https://manjaro.org/privacy-policy/"
LOGO=manjarolinux
```

### How did you install Apptainer

https://archlinux.org/packages/extra/x86_64/apptainer/

**Comment by GodloveD** [comment] 2023-10-23 15:05
I think this issue is fixed in later versions of Apptainer but @DrDaveD will have more details.

**Comment by DrDaveD** [comment] 2023-10-23 22:24
No I don't think it is fixed later.  If  you're following the instructions you're probably getting the latest install-unrivileged.sh, but nobody has reported trying it on an arch-based Linux before.  It doesn't sound like it's going to be very easy to adapt either.  What do you think about running install-unprivileged.sh on a more mainline distro, and copying the installation from there onto your machine?  I think that should work.

**Comment by DrDaveD** [comment] 2023-10-23 22:33
Oh, and GLIBC is backward compatible, but the problem is when we try to bring in code from a newer GLIBC on the host into an older container, we put it into a forward compatible situation, which it is not.

You can also avoid this by setting up /etc/subuid and /etc/subgid mapping for yourself, because then apptainer will not try to bind in the fakeroot command from the host, it will instead use the privileged newuidmap and newgidmap programs to set up a range of user ids in the user namespace.

**Comment by matekelemen** [comment] 2023-10-24 17:18
> running install-unprivileged.sh on a more mainline distro, and copying the installation from there onto your machine

Alright, I'll try that first; thanks for the tip!

**Comment by sorenwacker** [comment] 2024-03-19 10:59
Where is `install-unprivileged.sh` comming from?

**Comment by DrDaveD** [comment] 2024-03-19 12:07
https://apptainer.org/docs/admin/latest/installation.html#install-unprivileged-from-pre-built-binaries

**Closed** 2024-03-19 16:26 UTC
