### ISSUE TITLE
`findOnPath` fails to find `newuidmap` in non-standard search paths

### ISSUE THREAD

**Issue by ShamrockLee** [apptainer/apptainer#205] opened 2022-02-03 14:01 UTC
Moved here from https://github.com/apptainer/singularity/issues/6363

### Version of Apptainer:

What version of Apptainer are you using? Run:

```
$ singularity --version
singularity version 3.8.4
```

### Expected behavior

1.  `newuidmap` and `newgidmap` are found in directories prefixed in the `PATH` environment variable.
2.  `singularity build --fakeroot` works.

### Actual behavior

After running `singularity build --fakeroot` (in a Nix expression with `shadow` provided)

```
       > PATH is /nix/store/k1a6qkjw9m6b3r100i0w2qknl0g6ll31-singularity-3.8.4/bin:/nix/store/k21halap3i7hgglxpdnpx29538g3irin-coreutils-9.0/bin:/nix/store/ki4j2cwwm8p2www0071ss8mja20dkzbb-squashfs-4.5/bin:/nix/store/2aq9imyh2m0wglfbp00m35rgfyqaqww3-shadow-4.8.1/bin:/nix/store/xfb60lr4bh1dgn93cswif4j3gadfpjyp-xAna_monoZ_preselect-0.0.1/bin:/nix/store/y5dkkfin05252783r42vc38s83297ypv-patchelf-0.13/bin:/nix/store/k21halap3i7hgglxpdnpx29538g3irin-coreutils-9.0/bin:/nix/store/bfbsy0kyb3r2azfh9dimgqa1qxplkwgl-findutils-4.8.0/bin:/nix/store/9dpl3qwz7ziwx9cssj36zlca4q4wya4h-diffutils-3.8/bin:/nix/store/lwgh498dp39g9pnnaa8im4c4kkb1b4m0-gnused-4.8/bin:/nix/store/1m0rkfgnj9rlbp2jd3iz5h2lpv60ngxh-gnugrep-3.7/bin:/nix/store/xa8vlasjm4g7bqdijmwzbh077cbs6k2h-gawk-5.1.1/bin:/nix/store/gxzcls54jx8f7a8vcglwzsgkkizzrwnp-gnutar-1.34/bin:/nix/store/z3kr7132d3rncaaj2pch6fiw5bz8bpmd-gzip-1.11/bin:/nix/store/cdxwlsm848djwc86f4dqj47sd4byq0rk-bzip2-1.0.6.0.2-bin/bin:/nix/store/40qfhd1jlk4nrlilyh7s9mf3f3k65bw1-gnumake-4.3/bin:/nix/store/vfai0jim0db67nk9rd7ziq29jxb5n79n-bash-5.1-p8/bin:/nix/store/bdvz1ilv1x2qh45xa0qkfgb9vdrv5xa2-patch-2.7.6/bin:/nix/store/l5pns19l44hk17yr89l3i09bzx2nsgnr-xz-5.2.5-bin/bin
       > Executable newuidmap is /nix/store/2aq9imyh2m0wglfbp00m35rgfyqaqww3-shadow-4.8.1/bin/newuidmap
       > Executable newgidmap is /nix/store/2aq9imyh2m0wglfbp00m35rgfyqaqww3-shadow-4.8.1/bin/newgidmap
       > FATAL:   newuidmap was not found in PATH (/usr/bin:/usr/sbin:/bin:/sbin:/usr/local/bin:/usr/local/sbin), required with fakeroot and unprivileged installation
```

### Steps to reproduce this behavior

`stub.def`
```Singularity
Bootstrap: scratch
```

```console
[shamrock@nixos-202104:/dev/shm]$ nix-shell -p singularity shadow

[nix-shell:/dev/shm]$ singularity build --fakeroot stub.sif stub.def
FATAL:   newuidmap was not found in PATH (/usr/bin:/usr/sbin:/bin:/sbin:/usr/local/bin:/usr/local/sbin), required with fakeroot and unprivileged installation

[nix-shell:/dev/shm]$ type -p newuidmap
/nix/store/jki00pcw0npk9hfmxc5ln41003225b1h-shadow-4.8.1/bin/newuidmap

[nix-shell:/dev/shm]$ echo $PATH
/nix/store/6kxhv6s36p5l3jylxzwvqn4qm3fjkb63-bash-interactive-4.4-p23/bin:/nix/store/m40wl6v6ayalys7l5x5iqif6qwjj1dsx-patchelf-0.12/bin:/nix/store/ryy81g8zv6c8fh0j10m6fdynrgrn239k-gcc-wrapper-9.3.0/bin:/nix/store/fvf3qjqa5qpcjjkq37pb6ypnk1mzhf5h-gcc-9.3.0/bin:/nix/store/ddmdl1fin14hpjvssa7b933661y3xgxg-glibc-2.31-74-bin/bin:/nix/store/vr96j3cxj75xsczl8pzrgsv1k57hcxyp-coreutils-8.31/bin:/nix/store/h8ibzi1f489avmhcz754chnrgr3dysjr-binutils-wrapper-2.31.1/bin:/nix/store/vfqlryhvm8063hs7ax9k2vb8wmch5v0v-binutils-2.31.1/bin:/nix/store/ddmdl1fin14hpjvssa7b933661y3xgxg-glibc-2.31-74-bin/bin:/nix/store/vr96j3cxj75xsczl8pzrgsv1k57hcxyp-coreutils-8.31/bin:/nix/store/d7zl264bdvkiqls47b4bj7v21wxi7p2n-singularity-3.6.4/bin:/nix/store/vr96j3cxj75xsczl8pzrgsv1k57hcxyp-coreutils-8.31/bin:/nix/store/d9j1hbbz8d2g620dsvga9n0l1qcdniz9-squashfs-4.4/bin:/nix/store/jki00pcw0npk9hfmxc5ln41003225b1h-shadow-4.8.1/bin:/nix/store/vr96j3cxj75xsczl8pzrgsv1k57hcxyp-coreutils-8.31/bin:/nix/store/ax8vv1ds6l81jx8cmflx3fvcl9jdxd2w-findutils-4.7.0/bin:/nix/store/m87blzdbjqhj1dghl5l2dqqnl9dhvarz-diffutils-3.7/bin:/nix/store/gdr4s4xx41n8krk9carr8amvncy8x3p3-gnused-4.8/bin:/nix/store/rxkghln0km9axapv94iz3pcsln6ricms-gnugrep-3.4/bin:/nix/store/b9j6qhmxpwfvga2bfxn1khjrv3v3qxg7-gawk-5.1.0/bin:/nix/store/k6ssslsxmvndgm056k7x4s75390sjfkz-gnutar-1.32/bin:/nix/store/2hh9fld5r11zhp3697pzjwmqag76yc54-gzip-1.10/bin:/nix/store/6v59a9iszrs0kxk1b79v7fasn9bwi79q-bzip2-1.0.6.0.1-bin/bin:/nix/store/7fqqkrz6m11793cw7by8wbn2q87za8ny-gnumake-4.3/bin:/nix/store/9ywr69qi622lrmx5nn88gk8jpmihy0dz-bash-4.4-p23/bin:/nix/store/5vpsaqjazidyfrpjx2z137jmqwn3f2ai-patch-2.7.6/bin:/nix/store/n5xz5y5wazbhrwa9s9cyv52dabx9qxsq-xz-5.2.5-bin/bin:/run/wrappers/bin:/home/shamrock/.nix-profile/bin:/etc/profiles/per-user/shamrock/bin:/nix/var/nix/profiles/default/bin:/run/current-system/sw/bin

```

### What OS/distro are you running

```
$ cat /etc/os-release
NAME=NixOS
ID=nixos
VERSION="21.05.20211019.8fe3b97 (Okapi)"
VERSION_CODENAME=okapi
VERSION_ID="21.05.20211019.8fe3b97"
PRETTY_NAME="NixOS 21.05 (Okapi)"
LOGO="nix-snowflake"
HOME_URL="https://nixos.org/"
DOCUMENTATION_URL="https://nixos.org/learn.html"
SUPPORT_URL="https://nixos.org/community.html"
BUG_REPORT_URL="https://github.com/NixOS/nixpkgs/issues"
```

### How did you install Apptainer
Through Nix.

`flake.nix`
```Nix
{
  inputs.nixpkgs.url = "github:NixOS/nixpkgs/nixos-21.11";
  # ...
}
```

`flake.lock`
```json
{
  # ...
  "nixpkgs": {
    "locked": {
      "lastModified": 1643247693,
      "narHash": "sha256-rmShxIuNjYBz4l83J0J++sug+MURUY1koPCzX4F8hfo=",
      "owner": "NixOS",
      "repo": "nixpkgs",
      "rev": "6c4b9f1a2fd761e2d384ef86cff0d208ca27fdca",
      "type": "github"
    },
    "original": {
      "owner": "NixOS",
      "ref": "nixos-21.11",
      "repo": "nixpkgs",
      "type": "github"
    }
  }
  # ..
}
```

**Comment by PaulCharlton** [comment] 2022-02-03 15:25
as designed.   see https://sylabs.io/guides/latest/user-guide/environment_and_metadata.html?highlight=singularityenv_#environment-from-the-host and http://apptainer.org/docs/user/main/environment_and_metadata.html#environment-from-the-host

If you want `PATH` to have specific values inside of the container, you must ensure that the container file system includes such path element (by copying from the host, bind-mount, or something similar), and you can set the PATH inside of the container via `APPTAINERENV_PATH` or set within `.def` file

cc: @ikaneshiro @DrDaveD

**Comment by ShamrockLee** [comment] 2022-02-04 02:53
@PaulCharlton 
`APPTAINERENV_PATH="$PATH" apptainer build --fakeroot my-image.sif my-image.def` doesn't solve the issue.

As `newuidmap` is required for `apptainer build --fakeroot`, I presume that it is needed before executing the startup script, and apptainer will search for it on the host. There seems no way for it to get copied into the container beforehand if the container is to build from scratch.

**Comment by DrDaveD** [comment] 2022-02-04 20:54
newuidmap does have to be on the host, not in the container, and it is expected to be in a standard path for security reasons.  It is installed with increased capability much like setuid, so it needs to be installed by the system administrator anyway.  The paths for quite a few support tools can be configured in /etc/singularity/singularity.conf, but that doesn't appear to be one of them.

**Comment by ShamrockLee** [comment] 2022-02-05 04:42
> newuidmap does have to be on the host, not in the container, and it is expected to be in a standard path for security reasons. It is installed with increased capability much like setuid, so it needs to be installed by the system administrator anyway. The paths for quite a few support tools can be configured in /etc/singularity/singularity.conf, but that doesn't appear to be one of them.

Now I understand. Thank you for your quick response.

The problem is that, some systems like NixOS and Guix doesn't put system packages under those "standard" location, and programs that hard-code the PATH are usually patched in [Nixpkgs](https://github.com/NixOS/nixpkgs).

**Comment by preney** [comment] 2022-02-05 19:32
NixOS, Guix, Gentoo Prefix, etc. and other configurations such as Compute Canada's (CC) HPC software set up (e.g., https://docs.computecanada.ca/wiki/Accessing_CVMFS), EasyBuild configurations, etc. certainly do not have all packages in standard locations (and even if there are "system packages" installed user's often shouldn't use those) so Apptainer should not simply hard-code standard locations. 

Perhaps it is simplest if Apptainer was able to be run in a mode where there are ZERO default/hard-coded/automatically mounted bind mounts including internationalization and timezone settings. Clearly this would require a person to manually bind mount literally everything that the container will need to run --but that should be okay since such does not have to be a default/"normal" setting of Apptainer.

**Comment by DrDaveD** [comment] 2022-02-08 23:09
I think the original request has been answered, closing.

**Closed by DrDaveD** 2022-02-08 23:09 UTC

**Comment by PaulCharlton** [comment] 2022-02-09 04:38
@preney re:

> Perhaps it is simplest if Apptainer was able to be run in a mode where there are ZERO default/hard-coded/automatically mounted bind mounts including internationalization and timezone settings. Clearly this would require a person to manually bind mount literally everything that the container will need to run

fun fact -- this is how I built all of my Docker container micro services for security reasons -- zero reliance on the host OS.  (especially the trusted Root CA for TLS -- who can actually "trust" 300+ different CA???)

**Comment by ShamrockLee** [comment] 2022-02-09 05:03
Update:
*   I found that the `defaultPath` patching in Nixpkgs failed because of upstream (here) code changes. ( https://github.com/NixOS/nixpkgs/pull/158486 )
*   `--fakeroot` is unusable even after patching, since it relies on setuid-ed `newuidmap` and `newgidmap`.

**Comment by DrDaveD** [comment] 2022-02-09 21:58
>     * `--fakeroot` is unusable without administrative intervention even after patching, since it relies on setuid-ed `newuidmap` and `newgidmap`.

That's correct.  `--fakeroot` uses more than one user id in a namespace, which is a privileged operation.  Unprivileged user namespaces can only map to one user id, the original one.  All others map to a "nobody" id, 65534.
