### ISSUE TITLE
rpm install on Rocky 9 not working. fuse2fs missing while availble

### ISSUE THREAD

**Issue by HBJI** [apptainer/apptainer#660] opened 2022-08-28 08:11 UTC
apptainer-1.1.0.rc.2-1.x86_64.rpm

Installation of rpm package on rocky linux 9 failed.
Package e2fsprogs-1.46.5-2.el9.x86_64 is already installed.
fuse2fs found in path. 
[root@rocky-9 ~]# yum install -y https://github.com/apptainer/apptainer/releases/download/v1.1.0-rc.2/apptainer-1.1.0.rc.2-1.x86_64.rpm
Failed to set locale, defaulting to C.UTF-8
Extra Packages for Enterprise Linux 9 - x86_64                                                                                                                      4.1 MB/s | 9.4 MB     00:02    
Last metadata expiration check: 0:00:03 ago on Sun Aug 28 09:41:03 2022.
apptainer-1.1.0.rc.2-1.x86_64.rpm                                                                                                                                   6.3 MB/s |  34 MB     00:05    
Error: 
 Problem: conflicting requests
  - nothing provides fuse2fs needed by apptainer-1.1.0~rc.2-1.x86_64
(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)

### Expected behavior
rpm installation should work if fuse2fs is installed
Installation from source successful.  

### Actual behavior

Even with fuse2fs install rpm isnatllation failed

### Steps to reproduce this behavior

yum install -y https://github.com/apptainer/apptainer/releases/download/v1.1.0-rc.2/apptainer-1.1.0.rc.2-1.x86_64.rpm

### What OS/distro are you running

[root@rocky-9 builddir]# cat /etc/os-release 
NAME="Rocky Linux"
VERSION="9.0 (Blue Onyx)"
ID="rocky"
ID_LIKE="rhel centos fedora"
VERSION_ID="9.0"
PLATFORM_ID="platform:el9"
PRETTY_NAME="Rocky Linux 9.0 (Blue Onyx)"
ANSI_COLOR="0;32"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:rocky:rocky:9::baseos"
HOME_URL="https://rockylinux.org/"
BUG_REPORT_URL="https://bugs.rockylinux.org/"
ROCKY_SUPPORT_PRODUCT="Rocky-Linux-9"
ROCKY_SUPPORT_PRODUCT_VERSION="9.0"
REDHAT_SUPPORT_PRODUCT="Rocky Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="9.0"

**Comment by DrDaveD** [comment] 2022-08-28 13:01
Thanks for the report.  This is a duplicate of #642.  As a workaround please install instead from epel-testing.

**Closed by DrDaveD** 2022-08-28 13:01 UTC
